name: Build AIO-switch-updater

on: 
  push:
  workflow_dispatch:

jobs:
  AIO-switch-updater:
    runs-on: ubuntu-latest
    #container: hamletdufromage/devkita64_devkitarm
    container: devkitpro/devkita64
    steps:
    - uses: actions/checkout@master

    - name: update repo
      run: |
        git config --global --add safe.directory $(pwd)
        git config --global --add safe.directory $(pwd)/TegraExplorer
        git config --global --add safe.directory $(pwd)/lib/borealis
        git submodule update --init --recursive

    - name: install dependencies
      run: |
        sudo apt update -y
        sudo apt install build-essential -y

    - name: Building aio-switch-updater
      run: |
        make -C aiosu-forwarder -f Makefile
        make -j$(nproc)
        
    - uses: actions/upload-artifact@master
      with:
        name: aio-switch-updater
        path: aio-switch-updater.nro
